DROP TABLE IF EXISTS endpoint_hit CASCADE;

CREATE TABLE IF NOT EXISTS hits (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              app VARCHAR,
              uri VARCHAR,
              ip VARCHAR,
              timestamp TIMESTAMP WITHOUT TIME ZONE
);