DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS compilation_events CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS participation_request CASCADE;

CREATE TABLE IF NOT EXISTS users (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name VARCHAR(250) NOT NULL,
              email VARCHAR(254) NOT NULL,
              UNIQUE(email)
);

CREATE TABLE IF NOT EXISTS categories (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name VARCHAR(50) NOT NULL,
              UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS compilations (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              pinned Boolean NOT NULL,
              title VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              annotation VARCHAR(2000) NOT NULL,
              description VARCHAR(7000) NOT NULL,
              user_id BIGINT NOT NULL,
              category_id BIGINT NOT NULL,
              created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
              event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
              published_on TIMESTAMP WITHOUT TIME ZONE,
              lat FLOAT NOT NULL,
              lon FLOAT NOT NULL,
              paid Boolean NOT NULL,
              request_moderation Boolean NOT NULL,
              participant_limit INTEGER NOT NULL,
              confirmed_requests BIGINT,
              event_state VARCHAR NOT NULL CHECK (event_state IN ('PENDING', 'PUBLISHED', 'CANCELED')),
              title VARCHAR(120) NOT NULL,
              CONSTRAINT fk_events_to_users FOREIGN KEY(user_id) REFERENCES users(id),
              CONSTRAINT fk_events_to_categories FOREIGN KEY(category_id) REFERENCES categories(id)
);

CREATE TABLE IF NOT EXISTS compilation_events (
              compilation_id BIGINT NOT NULL,
              event_id BIGINT NOT NULL,
              PRIMARY KEY (compilation_id, event_id),
              CONSTRAINT fk_compilation_events_compilation FOREIGN KEY (compilation_id) REFERENCES compilations(id) ON DELETE CASCADE,
              CONSTRAINT fk_compilation_events_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS participation_request (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
              event_id BIGINT NOT NULL,
              requester_id BIGINT NOT NULL,
              request_status VARCHAR NOT NULL CHECK (request_status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED')),
              CONSTRAINT fk_participation_request_to_events FOREIGN KEY(event_id) REFERENCES events(id) ON DELETE CASCADE,
              CONSTRAINT fk_participation_request_to_users FOREIGN KEY(requester_id) REFERENCES users(id) ON DELETE CASCADE
);